# Generated by Django 5.2.7 on 2025-11-25 17:19

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('renewal_period_years', models.IntegerField(blank=True, null=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='certifications.certification')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('version', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('next_version_date', models.DateField(blank=True, null=True, verbose_name='New Version Release Date')),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('guide', models.URLField(blank=True, verbose_name='Exam Guide')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Duration')),
                ('question_count', models.IntegerField(blank=True, null=True)),
                ('question_format', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MC', 'Multiple Choice'), ('TF', 'True/False'), ('FILL', 'Fill in the Blank'), ('ORDER', 'Ordering'), ('MATCH', 'Matching / Drag and Drop'), ('CASE', 'Case Study'), ('SIM', 'Simulation'), ('LAB', 'Lab'), ('CODE', 'Coding'), ('SHORTA', 'Short Answer'), ('ESSAY', 'Essay'), ('PBA', 'Performance-Based Assessment'), ('PBQ', 'Performance-Based Question'), ('ORAL', 'Oral Exam'), ('OTHER', 'Other')], max_length=72)),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_pass_fail', models.BooleanField(default=False, verbose_name='Pass/Fail')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.certification')),
                ('tags', models.ManyToManyField(blank=True, to='home.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ExamDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_weight_percentage', models.DecimalField(blank=True, decimal_places=0, help_text='Minimum weight percentage for this domain.', max_digits=3, null=True)),
                ('max_weight_percentage', models.DecimalField(blank=True, decimal_places=0, help_text='Maximum weight percentage for this domain.', max_digits=3, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamDomainObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.examdomain')),
            ],
        ),
    ]
