# Generated by Django 5.2.7 on 2025-11-25 21:12

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='badge',
            field=models.ImageField(blank=True, upload_to='certification_badges/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Certifications that are prerequisites for this certification.', to='certifications.certification'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_format',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MC', 'Multiple Choice'), ('MS', 'Multiple Select'), ('TF', 'True/False'), ('FILL', 'Fill in the Blank'), ('ORDER', 'Ordering'), ('MATCH', 'Matching / Drag and Drop'), ('CASE', 'Case Study'), ('SIM', 'Simulation'), ('LAB', 'Lab'), ('CODE', 'Coding'), ('SHORTA', 'Short Answer'), ('ESSAY', 'Essay'), ('PBA', 'Performance-Based Assessment'), ('PBQ', 'Performance-Based Question'), ('ORAL', 'Oral Exam'), ('OTHER', 'Other')], max_length=75),
        ),
    ]
