# Generated by Django 5.2.7 on 2025-11-25 17:19

import django.db.models.deletion
import modules.goals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low'), (5, 'Optional')], default=3)),
                ('due_date', models.DateTimeField(default=modules.goals.models.get_default_due_date)),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certifications.certification')),
            ],
            options={
                'ordering': ['priority', '-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.objective')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('source_type', models.IntegerField(choices=[(1, 'Tutorial'), (2, 'Article'), (3, 'Video'), (4, 'Book'), (5, 'Course'), (6, 'Lecture'), (7, 'Lab'), (8, 'Project'), (9, 'Exam'), (10, 'Other')], default=10)),
                ('progress', models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Completed'), (4, 'Reviewed')], default=1)),
                ('is_assimilated', models.BooleanField(default=False, help_text='Indicates whether the content is fully understood and assimilated.', verbose_name='Clear understanding of content')),
                ('tags', models.ManyToManyField(blank=True, to='home.tag')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['priority', '-due_date'], name='priority_due_date_idx'),
        ),
    ]
