# Generated by Django 5.2.7 on 2025-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tag_type', models.CharField(choices=[('concept', 'Concept'), ('tech', 'Technology'), ('service', 'Service'), ('product', 'Product'), ('tool', 'Tool'), ('platform', 'Platform'), ('language', 'Language'), ('library', 'Library'), ('framework', 'Framework'), ('database', 'Database'), ('skill', 'Skill'), ('certification', 'Certification'), ('provider', 'Provider'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
